name: Continuous Delivery Publish on Container Registry  ( this is the equivalent for docker container )


on:
  release:
    types: [published]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/orion_api_and_dashboard_docker_image:latest

jobs:
  push_to_registry:
    name: Push Docker image to Container Registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
       - name: Checkout Code
         uses: actions/checkout@v4

       - name: Install Node
         uses: actions/setup-node@v4
         with:
          node-version: 20.x

       - name: Install Dependencies
         run: npm install

       - name: Build Project
         run:  npm run build
      
       - name: Log in to the Container registry
         uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
         with:
              registry: ${{ env.REGISTRY }}
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}


       - name: Extract metadata (tags, labels) for Docker
         id: meta
         uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
         with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

                
       - name: Publish
         run: |
                docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

