name: Continuous Delivery - Publish package to GitHub Packages ( this is equivalent of npm registry)

on:
  release:
    types: [published]
  workflow_dispatch:
    
env:
 NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  push_to_github_package:
    name: Push npm image to npm githuh package
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
       - name: Checkout Code
         uses: actions/checkout@v4

       - name: Install Node
         uses: actions/setup-node@v4
         with:
          node-version: 20.x
          registry-url: 'https://npm.pkg.github.com'

       - run: npm ci
       - run: npm publish
      
       

