ALTER TABLE "Vendors" ADD COLUMN IF NOT EXISTS "LogoUrl" character varying(2048);
ALTER TABLE "Products" ADD COLUMN IF NOT EXISTS "AttributesJson" text NOT NULL DEFAULT '{}';
ALTER TABLE "Categories" ADD COLUMN IF NOT EXISTS "ParentCategoryId" uuid;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Categories_Categories_ParentCategoryId'
        AND conrelid = '"Categories"'::regclass) THEN
        ALTER TABLE "Categories" ADD CONSTRAINT "FK_Categories_Categories_ParentCategoryId"
            FOREIGN KEY ("ParentCategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT;
    END IF;
END $$;

DROP INDEX IF EXISTS "IX_Categories_TenantId_Name";
CREATE UNIQUE INDEX "IX_Categories_TenantId_Name"
    ON "Categories" ("TenantId", "Name") WHERE "ParentCategoryId" IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Categories_TenantId_ParentCategoryId_Name"
    ON "Categories" ("TenantId", "ParentCategoryId", "Name") WHERE "ParentCategoryId" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "IX_Categories_ParentCategoryId" ON "Categories" ("ParentCategoryId");

CREATE TABLE IF NOT EXISTS "CategoryFields" (
    "Id" uuid PRIMARY KEY,
    "TenantId" character varying(80) NOT NULL,
    "CategoryId" uuid NOT NULL REFERENCES "Categories" ("Id") ON DELETE CASCADE,
    "Key" character varying(80) NOT NULL,
    "Label" character varying(160) NOT NULL,
    "DataType" character varying(32) NOT NULL,
    "Required" boolean NOT NULL,
    "Placeholder" character varying(240),
    "OptionsJson" text NOT NULL,
    "Min" numeric(18,4),
    "Max" numeric(18,4),
    "MaxLength" integer,
    "SortOrder" integer NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_CategoryFields_CategoryId_Key"
    ON "CategoryFields" ("CategoryId", "Key");

CREATE TABLE IF NOT EXISTS "ChatConversations" (
    "Id" uuid PRIMARY KEY,
    "TenantId" character varying(80) NOT NULL,
    "VendorId" uuid NOT NULL REFERENCES "Vendors" ("Id") ON DELETE RESTRICT,
    "CustomerId" uuid NOT NULL REFERENCES "Customers" ("Id") ON DELETE RESTRICT,
    "CustomerSubject" character varying(80) NOT NULL,
    "ProductId" uuid REFERENCES "Products" ("Id") ON DELETE SET NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CustomerLastReadMessageId" bigint NOT NULL,
    "VendorLastReadMessageId" bigint NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ChatConversations_TenantId_VendorId_CustomerSubject"
    ON "ChatConversations" ("TenantId", "VendorId", "CustomerSubject");
CREATE INDEX IF NOT EXISTS "IX_ChatConversations_TenantId_CustomerSubject_UpdatedAt"
    ON "ChatConversations" ("TenantId", "CustomerSubject", "UpdatedAt");
CREATE INDEX IF NOT EXISTS "IX_ChatConversations_CustomerId" ON "ChatConversations" ("CustomerId");
CREATE INDEX IF NOT EXISTS "IX_ChatConversations_VendorId" ON "ChatConversations" ("VendorId");
CREATE INDEX IF NOT EXISTS "IX_ChatConversations_ProductId" ON "ChatConversations" ("ProductId");

CREATE TABLE IF NOT EXISTS "ChatMessages" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenantId" character varying(80) NOT NULL,
    "ConversationId" uuid NOT NULL REFERENCES "ChatConversations" ("Id") ON DELETE CASCADE,
    "SenderRole" character varying(16) NOT NULL,
    "SenderId" character varying(80) NOT NULL,
    "ClientMessageId" uuid NOT NULL,
    "Content" character varying(4000) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ChatMessages_ConversationId_SenderRole_SenderId_ClientMessageId"
    ON "ChatMessages" ("ConversationId", "SenderRole", "SenderId", "ClientMessageId");
CREATE INDEX IF NOT EXISTS "IX_ChatMessages_ConversationId_Id"
    ON "ChatMessages" ("ConversationId", "Id");
